# Generated by Django 4.0.8 on 2026-02-13 05:05

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_essayquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='figure',
            field=models.ImageField(blank=True, help_text='Add an image for the question if necessary.', upload_to='uploads/%Y/%m/%d', validators=[core.validators.validate_image_type], verbose_name='Figure'),
        ),
    ]
